# Config file for automatic testing at travis-ci.org

language: python
os: linux
dist: focal

python:
  - "2.7"
  - "3.8"
  - "pypy2"
  - "pypy3"

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - rm -rf build/

script: ./script/test -vv

# setting sudo to 'false' allows running on travis-ci new infra (docker)
sudo: false
